name: System Update

on:
  workflow_dispatch:  # Allows manual triggering
  schedule:
    - cron: '0 3 * * *'  # Runs daily at 3 AM UTC

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Email Environment Variable
        run: echo "EMAIL_RECIPIENT=${{ secrets.EMAIL_RECIPIENT }}" >> $GITHUB_ENV

      - name: Grant Execute Permissions to the Script
        run: chmod +x update.sh

      - name: Run Update Script
        run: ./update.sh
